---
# General settings
macbook_homebrew_bin: /opt/homebrew/bin

# Terminal settings
terminal_profile_name: "Sandro"
terminal_font_size: 16
iterm2_profile_name: "Sandro Font"
iterm2_profile_guid: "6DDD3F76-8C2C-4C4A-9D6D-31B9A2E6A111"
iterm2_ascii_font: "JetBrainsMonoNL-Regular 16"
iterm2_non_ascii_font: "JetBrainsMonoNL-Regular 16"

# Dock settings
macbook_dock_apps:
  - /System/Library/CoreServices/Finder.app
  - /System/Applications/App Store.app
  - /System/Applications/Mail.app
  - /System/Applications/System Settings.app
  - /System/Applications/Preview.app
  - /System/Applications/Utilities/Terminal.app