---
# General settings
macbook_homebrew_bin: /opt/homebrew/bin
macbook_sbedit_binary: /usr/local/bin/sbedit
macbook_sbedit_root: "{{ ansible_env.HOME }}/.local/src/sidebar-editor"
macbook_sbedit_pkg: "{{ macbook_sbedit_root }}/sbedit-package/000sbedit-1.2/000sbedit-1.2.pkg"

# Terminal settings
terminal_profile_name: "Sandro"
terminal_font_size: 16
iterm2_profile_name: "Sandro Font"
iterm2_profile_guid: "6DDD3F76-8C2C-4C4A-9D6D-31B9A2E6A111"
iterm2_ascii_font: "JetBrainsMonoNL-Regular 16"
iterm2_non_ascii_font: "JetBrainsMonoNL-Regular 16"

# Dock settings
macbook_dock_apps:
  - /System/Applications/App Store.app
  - /System/Applications/Mail.app
  - /System/Applications/System Settings.app
  - /System/Applications/Preview.app
  - /System/Applications/Utilities/Terminal.app

# Finder settings
macbook_finder_sidebar_items:
  - /System/Library/CoreServices/Finder.app/Contents/Applications/AirDrop.app
  - /Applications
  - "{{ ansible_env.HOME }}/Documents"
  - "{{ ansible_env.HOME }}/Downloads"
  - "{{ ansible_env.HOME }}"