---
- block:

  - name: macbook | brew | update & upgrade all packages
    community.general.homebrew:
      update_homebrew: true
      upgrade_all: true
    when: brew_upgrade | default(false)

  - name: macbook | brew | install formulae
    community.general.homebrew:
      name: "{{ brew_formulae }}"
      state: present

  - name: macbook | brew | install casks
    community.general.homebrew_cask:
      name: "{{ brew_casks }}"
      state: present

  become: false
