# tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

# run roles

- hosts: all
  tags: base
  become: true
  roles:
    - base
    - docker

- hosts: tower
  tags: ricing
  become: true
  roles:
    - customize_tower

- hosts: mac
  tags: macbook
  become: true
  roles:
    - macbook

- hosts: server
  tags: server
  become: true
  roles:
    - server

# end of run cleanup and reporting
- hosts: all
  become: true
  tasks:
  - name: cleanup package cache (debian and ubuntu)
    tags: always
    apt:
      autoclean: yes
    changed_when: False
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: autoremove orphan packages (debian and ubuntu)
    tags: always
    apt:
      autoremove: yes
      purge: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

# add send completion and failure alret!
