- block:
    # Specific mac terminal settings (Terminal.app and iTerm2)
    - name: macbook | system setup | terminal
      import_tasks: system_setup/terminal.yml

    # Keyboard settings
    - name: macbook | system setup | keyboard
      import_tasks: system_setup/keyboard.yml

    # Dock settings
    - name: macbook | system setup | dock
      import_tasks: system_setup/dock.yml

    # Siri settings
    - name: macbook | system setup | siri
      import_tasks: system_setup/siri.yml

  when: ansible_os_family == "Darwin"