- block:

    - name: macbook | finder | set default folder to Home-folder
      community.general.osx_defaults:
        domain: com.apple.finder
        key: NewWindowTarget
        type: string
        value: PfLo

  become: false