- name: users | root | ensure account is locked
  user:
    name: root
    password_lock: yes

- name: users | root | create config directories
  file:
    path: /root/{{ item.dir }}
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
    - { dir: '.vim' }
    - { dir: '.vim/colors' }
  tags: dotfiles
