- name: users | sandro | create group
  tags: groups, sandro, users
  group:
    name: sandro
    state: present

- name: users | sandro | create user
  tags: sandro, sudo, users
  user:
    name: sandro
    group: sandro
    groups: adm, {{ sudo_group }}
    state: present
    comment: "Sandro main"
    password: "{{ sandro_passwd }}"
    shell: /bin/bash

- name: users | sandro | add sudoers file
  tags: sandro, settings, simone, sudo, system, users
  copy:
    src: users/sudoers_sandro
    dest: /etc/sudoers.d/sandro
    owner: root
    group: root
    mode: 0440

- name: users | sandro | create .ssh directory
  tags: dotfiles, sandro, ssh, users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: sandro
    group: sandro
    mode: 0700
  with_items:
    - { dir: '/home/sandro/.ssh' }

- name: users | sandro | add public key
  tags: dotfiles, sandro, ssh, ssh-keys, users
  authorized_key:
    user: sandro
    key: "{{ item }}"
  with_file:
    - users/sandro/ssh/id_ed25519.pub

- name: users | sandro | create config directories
  tags: dotfiles, sandro, tmux, users, vim, zsh
  file:
    path: /home/sandro/{{ item.dir }}
    state: directory
    owner: sandro
    group: sandro
    mode: 0700
  with_items:
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: '.config/htop' }
    - { dir: '.config/mc' }
    - { dir: '.tmux' }
    - { dir: '.tmux/config' }
    - { dir: '.tmux/plugins' }
    - { dir: '.vim' }
    - { dir: '.vim/autoload' }
    - { dir: '.vim/bundle' }
    - { dir: '.vim/colors' }
    - { dir: '.vim/ftplugin' }
    - { dir: '.zsh' }

- name: users | sandro | copy tmux config (server version)
  tags: dotfiles, users, sandro, tmux
  copy:
    src: users/sandro/tmux/tmux.conf.server
    dest: /home/sandro/.tmux.conf
    owner: sandro
    group: sandro
    mode: 0600
  when: "'server' in group_names"


- name: users | sandro | copy tmux config (workstation version)
  tags: dotfiles, users, sandro, tmux
  copy:
    src: users/sandro/tmux/tmux.conf.workstation
    dest: /home/sandro/.tmux.conf
    owner: sandro
    group: sandro
    mode: 0600
  when: "'server' not in group_names"

- name: users | sandro | copy dotfiles
  tags: dotfiles,users,sandro,tmux,users,vim,zsh
  copy:
    src: users/sandro/{{ item.src }}
    dest: /home/sandro/{{ item.dest }}
    owner: sandro
    group: sandro
    mode: 0600
  with_items:
    - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
    - { src: 'bash/bash_profile', dest: '.bash_profile' }
    - { src: 'bash/bash_prompt', dest: '.bash/bash_prompt' }
    - { src: 'bash/bash_functions', dest: '.bash/bash_functions' }
    - { src: 'bash/bashrc', dest: '.bashrc' }
    - { src: 'bash/profile', dest: '.profile' }
    - { src: 'git/gitconfig', dest: '.gitconfig' }
    - { src: 'htop/htoprc', dest: '.config/htop/htoprc' }
    - { src: 'inputrc', dest: '.inputrc' }
    - { src: 'mc/mc.ini', dest: '.config/mc/ini' }
    - { src: 'vim/vimrc', dest: '.vimrc' }
    - { src: 'zsh/zshrc', dest: '.zshrc' }

- name: users | sandro | clone tmux-completion plugin repository
  tags: dotfiles,sandro,users,tmux
  git:
    repo: https://github.com/srsudar/tmux-completion.git
    dest: /home/sandro/.tmux/plugins/completion
    force: yes
  notify: update_tmux_plugin_perms

- name: users | sandro | clone tmux-continuum plugin repository
  tags: dotfiles,sandro,users,tmux
  git:
    repo: https://github.com/tmux-plugins/tmux-continuum
    dest: /home/sandro/.tmux/plugins/continuum
    force: yes
  notify: update_tmux_plugin_perms

- name: users | sandro | clone tmux-resurrect plugin repository
  tags: dotfiles,sandro,users,tmux
  git:
    repo: https://github.com/tmux-plugins/tmux-resurrect
    dest: /home/sandro/.tmux/plugins/resurrect
    force: yes
  notify: update_tmux_plugin_perms

- name: users | sandr | clone tmux-pluginmanager plugin repository
  tags: dotfiles, sandro, users, tmux
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/sandro/.tmux/plugins/tpm
    force: yes
  notify: update_tmux_plugin_perms

- name: users | sandro | copy individual zsh config files
  tags: dotfiles,sandro,users,zsh
  copy:
    src: users/sandro/zsh/{{ item.src }}
    dest: /home/sandro/.zsh/{{ item.src }}
    owner: sandro
    group: sandro
    mode: 0600
  with_items:
    - { src: 'aliases.zsh' }
    - { src: 'bindkey.zsh' }
    - { src: 'completion.zsh' }
    - { src: 'exports.zsh' }
    - { src: 'functions.zsh' }
    - { src: 'history.zsh' }
    - { src: 'path.zsh' }
    - { src: 'plugins.zsh' }
    - { src: 'prompt.zsh' }
    - { src: 'setopt.zsh' }
    - { src: 'theming.zsh' }

- name: users | sandro | copy vim ftype files
  tags: dotfiles,sandro,users,vim
  copy:
    src: users/sandro/vim/{{ item.src }}
    dest: /home/sandro/.vim/ftplugin/{{ item.src }}
    owner: sandro
    group: sandro
    mode: 0600
  with_items:
    - { src: 'html.vim' }
    - { src: 'python.vim' }
    - { src: 'sql.vim' }
    - { src: 'xml.vim' }

- name: users | sandro | copy vim color files
  tags: dotfiles,sandro,users,vim
  copy:
    src: users/sandro/vim/{{ item.src }}
    dest: /home/sandro/.vim/colors/{{ item.src }}
    owner: sandro
    group: sandro
    mode: 0600
  with_items:
    - { src: 'bubblegum-256-dark.vim' }
    - { src: 'darktango.vim' }
    - { src: 'jellybeans.vim' }
    - { src: 'xoria256.vim' }
    - { src: 'zenburn.vim' }

- name: users | sandro | install pathogen
  tags: dotfiles,sandro,users,vim
  copy:
    src: users/sandro/vim/{{ item.src }}
    dest: "{{ item.dest }}"
    owner: sandro
    group: sandro
    mode: 0700
  with_items:
    - { src: 'pathogen.vim', dest: '/home/sandro/.vim/autoload/pathogen.vim' }

- name: users | sandro | checkout git repositories
  tags: git,users,sandro
  become: yes
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    force: yes
  with_items:
    - { repo: 'https://github.com/ctrlpvim/ctrlp.vim.git', dest: '/home/sandro/.vim/bundle/ctrlp.vim' }
    - { repo: 'https://github.com/davidhalter/jedi-vim.git', dest: '/home/sandro/.vim/bundle/jedi-vim' }
    - { repo: 'https://github.com/pearofducks/ansible-vim', dest: '/home/sandro/.vim/bundle/ansible-vim' }
    - { repo: 'https://github.com/rhysd/vim-grammarous.git', dest: '/home/sandro/.vim/bundle/vim-grammarous' }
    - { repo: 'https://github.com/ron89/thesaurus_query.vim', dest: '/home/sandro/.vim/bundle/thesaurus_query' }
    - { repo: 'https://github.com/scrooloose/nerdtree.git', dest: '/home/sandro/.vim/bundle/nerdtree' }
    - { repo: 'https://github.com/tpope/vim-obsession.git', dest: '/home/sandro/.vim/bundle/vim-obsession' }
    - { repo: 'https://github.com/vim-syntastic/syntastic.git', dest: '/home/sandro/.vim/bundle/syntastic' }
  notify: update_vim_bundle_perms
