- name: users | sandro | create group
  tags: groups, sandro, users
  group:
    name: sandro
    state: present

- name: users | sandro | create user
  tags: sandro, sudo, users
  user:
    name: sandro
    group: sandro
    groups: adm, {{ sudo_group }}
    state: present
    comment: "Sandro main"
    password: "{{ sandro_passwd }}"
    shell: /bin/bash

- name: users | sandro | add sudoers file
  tags: sandro, settings, simone, sudo, system, users
  copy:
    src: users/sudoers_sandro
    dest: /etc/sudoers.d/sandro
    owner: root
    group: root
    mode: 0440

- name: users | sandro | create .ssh directory
  tags: dotfiles, sandro, ssh, users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: sandro
    group: sandro
    mode: 0700
  with_items:
    - { dir: '/home/sandro/.ssh' }

- name: users | sandro | add public key
  tags: dotfiles, sandro, ssh, ssh-keys, users
  authorized_key:
    user: sandro
    key: "{{ item }}"
  with_file:
    - users/sandro/ssh/id_ed25519.pub

- name: users | sandro | create config directories
  tags: dotfiles, sandro, tmux, users, vim, zsh
  file:
    path: /home/sandro/{{ item.dir }}
    state: directory
    owner: sandro
    group: sandro
    mode: 0700
  with_items:
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: '.config/htop' }
    - { dir: '.config/mc' }
    - { dir: '.tmux' }
    - { dir: '.tmux/config' }
    - { dir: '.tmux/plugins' }
    - { dir: '.vim' }
    - { dir: '.vim/autoload' }
    - { dir: '.vim/bundle' }
    - { dir: '.vim/colors' }
    - { dir: '.vim/ftplugin' }
    - { dir: '.zsh' }

