---
- name: system setup | docker | get docker group info
  getent:
    database: group
    key: docker
    split: ':'
  when: docker_users | length > 0

- name: system setup | docker | check if at least one user needs docker group
  set_fact:
    at_least_one_user_to_modify: true
  when:
    - docker_users | length > 0
    - item not in ansible_facts.getent_group["docker"][2]
  loop: "{{ docker_users }}"

- name: system setup | docker | add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

- name: system setup | docker | reset ssh connection
  meta: reset_connection