- name: system setup | docker | remove old docker versions
  package:
    name:
      - docker
      - docker.io
      - docker-engine
    state: absent

- name: system setup | docker | install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  when: docker_add_repo | bool

- name: system setup | docker | add dependencies (on Ubuntu < 20.04)
  apt:
    name: gnupg2
    state: present
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is version('20.04', '<')

- name: system setup | docker | add dependencies (on Ubuntu >= 20.04).
  apt:
    name: gnupg
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('20.04', '>=')

- name: system setup | docker | change iptables to legacy
  tags: docker, iptables legacy, start docker
  community.general.alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
    link: /etc/alternatives/iptables
  notify: restart iptables
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version is version ('22.04')

- name: system setup | docker | apt key
  ansible.builtin.get_url:
    url: "{{ docker_apt_gpg_key }}"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: false
    checksum: "{{ docker_apt_gpg_key_checksum | default(omit) }}"
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"
  when: docker_add_repo | bool

- name: system setup | docker | curl (on older systems without SNI).
  package: name=curl state=present
  when: add_repository_key is failed and docker_add_repo | bool

- name: system setup | docker | add apt key (older systems without SNI).
  shell: >
    curl -sSL {{ docker_apt_gpg_key }} | apt-key add -
  when: add_repository_key is failed and docker_add_repo | bool

- name: system setup | docker | add docker repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    filename: "{{ docker_apt_filename }}"
    update_cache: true
  when: docker_add_repo | bool
