---
- name: software | Install unattended upgrades package | Ubuntu
  tags: software, upgrades package
  package:
    name: unattended-upgrades
    state: present

- name: software | Copy unattended-upgrades | Ubuntu
  tags: software, copy upgrades, ubuntu
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
