- name: corsair | install packages
  tags: corsair
  apt:
    name:
      - gdebi-core
      - qtbase5-dev
      - libusb-1.0-0-dev
      - qttools5-dev-tools
      - libmbedcrypto3
    state: present

- name: corsair | download OpenRGB .deb package
  tags: corsair
  get_url:
    url: https://openrgb.org/releases/release_0.9/openrgb_0.9_amd64_bullseye_b5f46e3.deb
    dest: /tmp/OpenRGB_0.9_amd64.deb

- name: corsair | install OpenRGB deb package
  tags: corsair
  apt:
    deb: /tmp/OpenRGB_0.9_amd64.deb

- name: corsair | deploy RGB color script for Commander PRO
  tags: corsair
  template:
    src: set_rgb_color.j2
    dest: /usr/local/bin/set_rgb_color.sh
    owner: root
    group: root
    mode: 0755
  vars:
    device_id: "{{ device_id }}"
    led_colors:
      0: "{{ led_col_0 }}"
      1: "{{ led_col_1 }}"
      2: "{{ led_col_2 }}"
      3: "{{ led_col_3 }}"
      4: "{{ led_col_4 }}"
      5: "{{ led_col_5 }}"
      6: "{{ led_col_6 }}"
