- name: corsair | install packages
  tags: corsair
  apt:
    name: gdebi-core
    state: present
  when: ansible_distribution == "Ubuntu"

- name: corsair | download OpenRGB .deb package
  tags: corsair
  get_url:
    url: https://openrgb.org/releases/release_0.9/OpenRGB_0.9_amd64.deb
    dest: /tmp/OpenRGB_0.9_amd64.deb

- name: corsair | install OpenRGB deb package
  tags: corsair
  apt:
    deb: /tmp/OpenRGB_0.9_amd64.deb
  when: ansible_distribution == "Ubuntu"
