- name: corsair | install packages
  tags: corsair
  apt:
    name:
      - qtbase5-dev
      - libusb-1.0-0-dev
      - qttools5-dev-tools
      - pkg-config
      - libhidapi-dev
      - libmbedtls-dev
    state: present

- name: corsair | clone OpenRGB source code from Gitlab
  tags: corsair
  git:
    repo: https://gitlab.com/CalcProgrammer1/OpenRGB.git
    dest: /opt/OpenRGB
    version: master

- name: corsair | run qmake to generate Makefile
  tags: corsair
  become: true
  command: qmake OpenRGB.pro
  args:
    chdir: /opt/OpenRGB

- name: corsair | build OpenRGB from source
  tags: corsair
  become: true
  command: make -j"{{ ansible_processor_cores | default(4) }}"
  args:
    chdir: /opt/OpenRGB

- name: corsair | deploy RGB color script for Commander PRO
  tags: corsair
  template:
    src: set_rgb_color.j2
    dest: /usr/local/bin/set_rgb_color.sh
    owner: root
    group: root
    mode: 0755
  vars:
    device_id: "{{ device_id }}"
    led_colors:
      0: "{{ led_col_0 }}"
      1: "{{ led_col_1 }}"
      2: "{{ led_col_2 }}"
      3: "{{ led_col_3 }}"
      4: "{{ led_col_4 }}"
      5: "{{ led_col_5 }}"
      6: "{{ led_col_6 }}"

- name: corsair | run color setting bash
  tags: corsair
  command: /usr/local/bin/set_rgb_color.sh
