---
branch: main

ansible_cron_minute: "40"

# platform-specific
microcode_amd_install: false
microcode_intel_install: false


# Autoupdate mail settings used on Debian/Ubuntu only
security_autoupdate_enabled: true
security_autoupdate_blacklist: [] #Packages that should not be updated
security_autoupdate_reboot: false #Wheter to reboot needed while auto upgrade
security_autoupdate_reboot_time: "03:00"

security_autoupdate_mail_to: "sandro.roth@hotmail.de"
security_autoupdate_mail_on_error: true

# Containerization collection
docker: true
portainer: true
