---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (ArchLinux)
    tags: always
    community.general.pacman:
      update_cache: true
    changed_when: false
    when: ansible_distribution == "Arch Linux"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAtR4qMGcvPgrfenhN5NvUUtMnWyuTKuJZ/fRYhm4Un/ ansible"

- hosts: web_server
  become: true
  tasks:

  - name: install apache and php package
    tags: apache,apache2,ubuntu
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

  - name: change e-mail address inside config file of admin
    tags: apache,ubuntu
    lineinfile:
      path: /etc/httpd/conf/http.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "Ubuntu"
    register: hoselupf

  - name: restart httpd (Ubuntu)
    tags: apache,Ubuntu,httpd
    service:
      name: httpd
      state: restarted
    when: hoselupf.changed

  - name: copy html file for site
    tags: apache,apche2,httpd
    copy:
      src: default_site.html
      dest: /var/ww/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: workstation
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: http://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      mode: 0755
      owner: root
      group: root


- hosts: workstation
  become: true
  tasks:

  - name: install mariadb package (ArchLinux)
    tags: archlinux,db,mariadb
    community.general.pacman:
      name: mariadb
      state: latest
    when: ansible_distribution == "Arch Linux"


  - name: start mariadb (ArchLInux)
    tags: mariadb,db,systemctl
    service:
      name: mariadb
      state: started
      enabled: yes
    when: ansible_distribution == "Arch Linux"
