---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (ArchLinux)
    tags: always
    community.general.pacman:
      update_cache: true
    changed_when: false
    when: ansible_distribution == "Arch Linux"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: web_server
  become: true
  roles:
    - server

- hosts: workstations
  become: true
  roles:
    - workstation
