---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (ArchLinux)
    tags: always
    community.general.pacman:
      update_cache: true
      upgrade: true
    when: ansible_distribution == "Arch Linux"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

  - name: install apache and php package
    tags: apache,apache2,ubuntu
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

  - name: copy html file for site
    tags: apache,apche2,httpd
    copy:
      src: default_site.html
      dest: /var/ww/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: workstation
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: http://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      mode: 0755
      owner: root
      group: root


- hosts: workstation
  become: true
  tasks:

  - name: install mariadb package (ArchLinux)
    tags: archlinux,db,mariadb
    community.general.pacman:
      name: mariadb
      state: latest
    when: ansible_distribution == "Arch Linux"
