# source bash prompt
source "$HOME/.bash/bash_prompt"

# source bash aliases
source "$HOME/.bash/bash_aliases"

# source bash functions
source "$HOME/.bash/bash_functions"

# env
export TERM=xterm-256color
export EDITOR=vim

# Homebrew on macOS
if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# show system information at login
if [ -t 0 ]; then
    if type -p "neofetch" > /dev/null; then
        neofetch
    else
        echo "Warning: neofetch was called, but it's not installed."
    fi
fi

# don't add duplicate lines or lines beginning with a space to the history
HISTCONTROL=ignoreboth

# set history format to include timestamps
HISTTIMEFORMAT="%Y-%m-%d %T "

# correct simple errors while using cd
shopt -s cdspell

# add $HOME/bin to PATH
case ":$PATH:" in
    *:"$HOME/bin":*) ;;
    *) PATH="$HOME/bin:$PATH" ;;
esac

# add $HOME/.local/bin to PATH
case ":$PATH:" in
    *:"$HOME/.local/bin":*) ;;
    *) PATH="$HOME/.local/bin:$PATH" ;;
esac

# enable tab completion for tmux
if [ -f "$HOME/.tmux/plugins/completion/tmux" ]; then
    source "$HOME/.tmux/plugins/completion/tmux"
fi

# add tmuxifier to PATH
case ":$PATH:" in
    *:"$HOME/.tmux/tmuxifier/bin":*) ;;
    *) PATH="$HOME/.tmux/tmuxifier/bin:$PATH" ;;
esac

export PATH

# reload bash config
alias reload='source "$HOME/.bashrc"'