- name: system setup | fail2ban | Install fail2ban (Ubuntu, Archlinux)
  tags: system, setup, fail2ban
  package:
    name: fail2ban
    state: present
  when: ansible_distribution in ["Ubuntu", "Archlinux"]

- name: system setup | fail2ban | Copy jail custom config file into place
  tags: system, setup, fail2ban, jailcustom
  template:
    src: "{{ security_fail2ban_custom_configuration_template }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify:
    - reload fail2ban

- name: system setup | fail2ban | handle erros in Ubuntu setups
  tags: system, setup, fail2ban, Ubuntu setup
  template:
    src: fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version | int >= 12
  notify:
    - reload fail2ban

- name: system setup | fail2ban | Ensure fail2ban is enabled and running
  tags: system, setup, fail2ban, boot enabled
  service:
    name: fail2ban
    state: started
    enabled: true
